LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := gps.$(TARGET_BOOTLOADER_BOARD_NAME)
LOCAL_SHARED_LIBRARIES := liblog libdl libcrypto
LOCAL_C_INCLUDES += external/openssl/include
LOCAL_SRC_FILES := gps.c
LOCAL_CFLAGS += -fno-short-enums
#LOCAL_CFLAGS += -DNEEDS_INITIAL_XTRA
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw

include $(BUILD_SHARED_LIBRARY)
